Feature/denomination
aergoio/aergo pull request #224
Opened 2023-06-26 01:56 UTC by gokch

## What is changed?
integrate denomination logic to types/denomination.go
improve readability of some config variables.

## Is there risk of fork? 
Unlikely happens. all config tested.

2023-06-26 07:40 UTC, gokch commented on cmd/aergocli/util/unit_test.go
>  func TestPasreUnit(t *testing.T) {
changed 8471e91100b5abee0180b18d699952b9ade53c60

2023-06-26 07:41 UTC, gokch commented on cmd/aergocli/util/unit_test.go
> -	assert.NoError(t, err, "parsing AERGO")
fixed 8471e91100b5abee0180b18d699952b9ade53c60

2023-06-26 07:41 UTC, gokch commented on cmd/aergocli/util/unit_test.go
>  func TestPasreDecimalUnit(t *testing.T) {
fixed 8471e91100b5abee0180b18d699952b9ade53c60

2023-06-26 07:42 UTC, gokch commented on contract/vm_dummy/vm_dummy_test.go
> +		NewLuaTxDeploy("user1", "deploy", types.Aergo/2, code),
fixed 8471e91100b5abee0180b18d699952b9ade53c60

2023-06-28 00:09 UTC, kroggen requested changes

2023-06-28 04:13 UTC, kroggen approved these changes

2023-06-28 04:58 UTC, merged